services:
  # Backend API Service
  - type: web
    name: atlan-helpdesk-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ACTIVELOOP_ORG
        sync: false
      - key: DEEPLAKE_TOKEN
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  # Frontend Static Site
  - type: web
    name: atlan-helpdesk-frontend
    env: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
